language: python
python:
    - 3.3
    - 3.4
    - 3.5

install:
    - pip install pep8 pep257

script: 
    - python setup.py install
    - pep8 *.py
    - pep257 * py
    - cd tests && ./test.sh

branches:
    only:
        - master
